version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - trail_race_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - trail_race_network

  race_application_command_service:
    build:
      context: ./race-application-command-service
      dockerfile: Dockerfile
    container_name: race_application_command_service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
    networks:
      - trail_race_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5


  race_application_query_service:
    build:
      context: ./race-application-query-service
      dockerfile: Dockerfile
    container_name: race_application_query_service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8082:8082"
    depends_on:
      - postgres_db
    networks:
      - trail_race_network

volumes:
  postgres_data:

networks:
  trail_race_network:
    name: trail_race_network
    driver: bridge
